### ISSUE TITLE
Packing binaries for easy download

### ISSUE THREAD

**Issue by obeliskos** [bfosterjr/windowsrtdev#1]
Thanks for your work compiling this archive of programs.  

To make it easier for others to download individual programs rather than the whole 800mb main branch, I would suggest : 
- setting up another mostly empty repo maybe with just a readme.md file, maybe call it WinrtReleases
- zip up all your bin folders individually, with a zip file per application binary package
- Above your new project page you will see 0 releases, click on it to create a new release
- When creating the release you can attach binaries to associate with the release, drop all your individual binary zip packages into the 'attach binaries' area of the new release screen
- Once you create the release, you releases page will have sharable links to each individual binary attachment

**Comment by bfosterjr** [comment]
Thanks for the suggestion. I encourage you to do this yourself. I have no free time to support these binaries beyond my own needs. Cheers!

**Comment by obeliskos** [comment]
hah ok thanks, I have little time for this myself.  hope you don't think I was complaining, you have provided a great resource here.

**Comment by bfosterjr** [comment]
Thought this issue has been closed, I just wanted to say that I've started packaging the apps into .zip files for easier download. Not exactly what you requested.. but should help.

**Comment by bfosterjr** [comment]
Though this issue has been closed, I just wanted to say that I've started packaging the apps into .zip files for easier download. Not exactly what you requested.. but should help.

**Comment by obeliskos** [comment]
Thanks, awesome that you are updating it with even newer builds like notepad++.  Are you building your windows sources (like notepad++) with vs2012?

**Comment by bfosterjr** [comment]
All of the original binaries were built with vs2012.  But i've switched to vs2013 for any new builds.
