### ISSUE TITLE
Reverting the signing commit

### ISSUE THREAD

**Issue by kika123** [bfosterjr/windowsrtdev#2]
The current RT 8.1 jailbreak(developer edition, has PatchGuard bypass) permits running really unsigned apps with ci_mod(which works because of the PG bypass) 
As such, apps no longer need to be signed

**Comment by bfosterjr** [comment]
which jailbreak are you referring too?

**Comment by kika123** [comment]
http://forum.xda-developers.com/devdb/project/?id=14813#downloads
It's the _DEV version of the jailbreak, which uses Meow, from Satoshi Tanda (github.com/tandasat/meow)

**Comment by bfosterjr** [comment]
Unless having the binaries signed is impacting their ability to run with this new JB.. I won't be reverting the signing commit.  Others rely on these binaries being signed.
