### ISSUE TITLE
Git?

### ISSUE THREAD

**Issue by santhoshmprabhu** [bfosterjr/windowsrtdev#3]
Could you please try to export git?

**Comment by bfosterjr** [comment]
?

**Comment by santhoshmprabhu** [comment]
I use git a lot for my work. Right now, I've managed to get jgit running on Windows RT, using Java. Could you please see if it's possible to make git available on Windows RT?

**Comment by bfosterjr** [comment]
Ah. I thought thats what you were requesting.

Honestly.. git.. for all its praise.. is not well written and would be difficult to port.  If there was a good client based on lib2git.. then that might be an option.
